.mode columns
.headers on
.nullvalue NULL
PRAGMA foreign_keys = ON;

DROP TRIGGER IF EXISTS addAgenda;
DROP TRIGGER IF EXISTS updateAgenda;

DELETE FROM PACIENTE WHERE idPaciente=400;
DELETE FROM AGENDA WHERE idAgenda=401;
DELETE FROM AGENDA WHERE idAgenda=402;
DELETE FROM AGENDA WHERE idAgenda=403;
